### ISSUE TITLE
Custom project on nRF9160

### ISSUE THREAD

**Issue by ncohenn** [thuan1091996/nrf91_projects#1]
Hi @thuan1091996 

I wanted to know if you would be available and interested in working on a new project on the nRF9160 to implement the AWS IoT fleet provisioning by claim. 

Looking forward to hearing from you 

Best Regards 
Nate

**Comment by thuan1091996** [comment]
Hello @ncohenn, 
Thank you for your interest! I would be happy to join your exciting project. I have sent you an email, please let me know if you received it. Alternatively, you can reach me at minhthuan1091996@gmail.com.

Thank you, and best regards,  
Thuan.
